version: '3.8'

services:
  finance-tracker-backend:
    build:
      context: .
      dockerfile: DockerFile
    container_name: finance-tracker-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGODB_URI=mongodb://mongodb:27017/finance_tracker
      - MONGODB_DATABASE=finance_tracker
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - finance-tracker-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/finance-tracker/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s

  mongodb:
    image: mongo:7.0
    container_name: finance-tracker-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - finance-tracker-network
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=finance_tracker
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  finance-tracker-network:
    driver: bridge

volumes:
  mongodb-data:

